/**
 * http://www.360doc.com/content/16/0116/21/2697712_528463222.shtml
 * https://developers.weixin.qq.com/miniprogram/dev/extended/component-plus/emoji.html
 */

const emojis_wx = [
  {
    emoji: '[微笑]',
    name: '微笑',
    em_code: '/::)',
    code: 'wx-1',
  },
  {
    emoji: '[撇嘴]',
    name: '撇嘴',
    em_code: '/::~',
    code: 'wx-2',
  },
  {
    emoji: '[色]',
    name: '色',
    em_code: '/::B',
    code: 'wx-3',
  },
  {
    emoji: '[发呆]',
    name: '发呆',
    em_code: '/::|',
    code: 'wx-4',
  },
  {
    emoji: '[得意]',
    name: '得意',
    em_code: '/:8-)',
    code: 'wx-5',
  },
  {
    emoji: '[流泪]',
    name: '流泪',
    em_code: '/::<',
    code: 'wx-6',
  },
  {
    emoji: '[害羞]',
    name: '害羞',
    em_code: '/::$',
    code: 'wx-7',
  },
  {
    emoji: '[闭嘴]',
    name: '闭嘴',
    em_code: '/::X',
    code: 'wx-8',
  },
  {
    emoji: '[睡]',
    name: '睡',
    em_code: '/::Z',
    code: 'wx-9',
  },
  {
    emoji: '[大哭]',
    name: '大哭',
    em_code: '/::’(',
    code: 'wx-10',
  },
  {
    emoji: '[尴尬]',
    name: '尴尬',
    em_code: '/::-|',
    code: 'wx-11',
  },
  {
    emoji: '[发怒]',
    name: '发怒',
    em_code: '/::@',
    code: 'wx-12',
  },
  {
    emoji: '[调皮]',
    name: '调皮',
    em_code: '/::P',
    code: 'wx-13',
  },
  {
    emoji: '[呲牙]',
    name: '呲牙',
    em_code: '/::D',
    code: 'wx-14',
  },
  {
    emoji: '[惊讶]',
    name: '惊讶',
    em_code: '/::O',
    code: 'wx-15',
  },
  // line2
  {
    emoji: '[难过]',
    name: '难过',
    em_code: '/::(',
    code: 'wx-16',
  },
  {
    emoji: '[酷]',
    name: '酷',
    em_code: '/::+',
    code: 'wx-17',
  },
  {
    emoji: '[囧]',
    name: '囧',
    em_code: '/:–b',
    code: 'wx-18',
  },
  {
    emoji: '[抓狂]',
    name: '抓狂',
    em_code: '/::Q',
    code: 'wx-19',
  },
  {
    emoji: '[吐]',
    name: '吐',
    em_code: '/::T',
    code: 'wx-20',
  },
  {
    emoji: '[偷笑]',
    name: '偷笑',
    em_code: '/:,@P',
    code: 'wx-21',
  },
  {
    emoji: '[愉快]',
    name: '愉快',
    em_code: '/:,@-D',
    code: 'wx-22',
  },
  {
    emoji: '[白眼]',
    name: '白眼',
    em_code: '/::d',
    code: 'wx-23',
  },
  {
    emoji: '[傲慢]',
    name: '傲慢',
    em_code: '/:,@o',
    code: 'wx-24',
  },
  {
    emoji: '[饥饿]',
    name: '饥饿',
    em_code: '/::g',
    code: 'wx-25',
  },
  {
    emoji: '[困]',
    name: '困',
    em_code: '/:|-)',
    code: 'wx-26',
  },
  {
    emoji: '[惊恐]',
    name: '惊恐',
    em_code: '/::!',
    code: 'wx-27',
  },
  {
    emoji: '[流汗]',
    name: '流汗',
    em_code: '/::L',
    code: 'wx-28',
  },
  {
    emoji: '[憨笑]',
    name: '憨笑',
    em_code: '/::>',
    code: 'wx-29',
  },
  {
    emoji: '[悠闲]',
    name: '悠闲',
    em_code: '/::,@',
    code: 'wx-30',
  },
  // line3
  {
    emoji: '[奋斗]',
    name: '奋斗',
    em_code: '/:,@f',
    code: 'wx-31',
  },
  {
    emoji: '[咒骂]',
    name: '咒骂',
    em_code: '/::-S',
    code: 'wx-32',
  },
  {
    emoji: '[疑问]',
    name: '疑问',
    em_code: '/:?',
    code: 'wx-33',
  },
  {
    emoji: '[嘘]',
    name: '嘘',
    em_code: '/:,@x',
    code: 'wx-34',
  },
  {
    emoji: '[晕]',
    name: '晕',
    em_code: '/:,@@',
    code: 'wx-35',
  },
  {
    emoji: '[疯了]',
    name: '疯了',
    em_code: '/::8',
    code: 'wx-36',
  },
  {
    emoji: '[衰]',
    name: '衰',
    em_code: '/:,@!',
    code: 'wx-37',
  },
  {
    emoji: '[骷髅]',
    name: '骷髅',
    em_code: '/:!!!',
    code: 'wx-38',
  },
  {
    emoji: '[敲打]',
    name: '敲打',
    em_code: '/:xx',
    code: 'wx-39',
  },
  {
    emoji: '[再见]',
    name: '再见',
    em_code: '/:bye',
    code: 'wx-40',
  },
  {
    emoji: '[擦汗]',
    name: '擦汗',
    em_code: '/:wipe',
    code: 'wx-41',
  },
  {
    emoji: '[抠鼻]',
    name: '抠鼻',
    em_code: '/:dig',
    code: 'wx-42',
  },
  {
    emoji: '[鼓掌]',
    name: '鼓掌',
    em_code: '/:handclap',
    code: 'wx-43',
  },
  {
    emoji: '[糗大了]',
    name: '糗大了',
    em_code: '/:&-(',
    code: 'wx-44',
  },
  {
    emoji: '[坏笑]',
    name: '坏笑',
    em_code: '/:B-)',
    code: 'wx-45',
  },
  // line4
  {
    emoji: '[左哼哼]',
    name: '左哼哼',
    em_code: '/:<@',
    code: 'wx-46',
  },
  {
    emoji: '[右哼哼]',
    name: '右哼哼',
    em_code: '/:@>',
    code: 'wx-47',
  },
  {
    emoji: '[哈欠]',
    name: '哈欠',
    em_code: '/::-O',
    code: 'wx-48',
  },
  {
    emoji: '[鄙视]',
    name: '鄙视',
    em_code: '/:>-|',
    code: 'wx-49',
  },
  {
    emoji: '[委屈]',
    name: '委屈',
    em_code: '/:P-(',
    code: 'wx-50',
  },
  {
    emoji: '[快哭了]',
    name: '快哭了',
    em_code: '/::’|',
    code: 'wx-51',
  },
  {
    emoji: '[阴险]',
    name: '阴险',
    em_code: '/:X-)',
    code: 'wx-52',
  },
  {
    emoji: '[亲亲]',
    name: '亲亲',
    em_code: '/::*',
    code: 'wx-53',
  },
  {
    emoji: '[吓]',
    name: '吓',
    em_code: '/:@x',
    code: 'wx-54',
  },
  {
    emoji: '[可怜]',
    name: '可怜',
    em_code: '/:8*',
    code: 'wx-55',
  },
  {
    emoji: '[菜刀]',
    name: '菜刀',
    em_code: '/:pd',
    code: 'wx-56',
  },
  {
    emoji: '[西瓜]',
    name: '西瓜',
    em_code: '/:<W>',
    code: 'wx-57',
  },
  {
    emoji: '[啤酒]',
    name: '啤酒',
    em_code: '/:beer',
    code: 'wx-58',
  },
  {
    emoji: '[篮球]',
    name: '篮球',
    em_code: '/:basketb',
    code: 'wx-59',
  },
  {
    emoji: '[乒乓]',
    name: '乒乓',
    em_code: '/:oo',
    code: 'wx-60',
  },
  // line5
  {
    emoji: '[咖啡]',
    name: '咖啡',
    em_code: '/:coffee',
    code: 'wx-61',
  },
  {
    emoji: '[饭]',
    name: '饭',
    em_code: '/:eat',
    code: 'wx-62',
  },
  {
    emoji: '[猪头]',
    name: '猪头',
    em_code: '/:pig',
    code: 'wx-63',
  },
  {
    emoji: '[玫瑰]',
    name: '玫瑰',
    em_code: '/:rose',
    code: 'wx-64',
  },
  {
    emoji: '[凋谢]',
    name: '凋谢',
    em_code: '/:fade',
    code: 'wx-65',
  },
  {
    emoji: '[嘴唇]',
    name: '嘴唇',
    em_code: '/:showlove',
    code: 'wx-66',
  },
  {
    emoji: '[爱心]',
    name: '爱心',
    em_code: '/:heart',
    code: 'wx-67',
  },
  {
    emoji: '[心碎]',
    name: '心碎',
    em_code: '/:break',
    code: 'wx-68',
  },
  {
    emoji: '[蛋糕]',
    name: '蛋糕',
    em_code: '/:cake',
    code: 'wx-69',
  },
  {
    emoji: '[闪电]',
    name: '闪电',
    em_code: '/:li',
    code: 'wx-70',
  },
  {
    emoji: '[炸弹]',
    name: '炸弹',
    em_code: '/:bome',
    code: 'wx-71',
  },
  {
    emoji: '[刀]',
    name: '刀',
    em_code: '/:kn',
    code: 'wx-72',
  },
  {
    emoji: '[足球]',
    name: '足球',
    em_code: '/:footb',
    code: 'wx-73',
  },
  {
    emoji: '[瓢虫]',
    name: '瓢虫',
    em_code: '/:ladybug',
    code: 'wx-74',
  },
  {
    emoji: '[便便]',
    name: '便便',
    em_code: '/:shit',
    code: 'wx-75',
  },
  // line6
  {
    emoji: '[月亮]',
    name: '月亮',
    em_code: '/:moon',
    code: 'wx-76',
  },
  {
    emoji: '[太阳]',
    name: '太阳',
    em_code: '/:sun',
    code: 'wx-77',
  },
  {
    emoji: '[礼物]',
    name: '礼物',
    em_code: '/:gift',
    code: 'wx-78',
  },
  {
    emoji: '[拥抱]',
    name: '拥抱',
    em_code: '/:hug',
    code: 'wx-79',
  },
  {
    emoji: '[强]',
    name: '强',
    em_code: '/:strong',
    code: 'wx-80',
  },
  {
    emoji: '[弱]',
    name: '弱',
    em_code: '/:weak',
    code: 'wx-81',
  },
  {
    emoji: '[握手]',
    name: '握手',
    em_code: '/:share',
    code: 'wx-82',
  },
  {
    emoji: '[胜利]',
    name: '胜利',
    em_code: '/:v',
    code: 'wx-83',
  },
  {
    emoji: '[抱拳]',
    name: '抱拳',
    em_code: '/:@)',
    code: 'wx-84',
  },
  {
    emoji: '[勾引]',
    name: '勾引',
    em_code: '/:jj',
    code: 'wx-85',
  },
  {
    emoji: '[拳头]',
    name: '拳头',
    em_code: '/:@@',
    code: 'wx-86',
  },
  {
    emoji: '[差劲]',
    name: '差劲',
    em_code: '/:bad',
    code: 'wx-87',
  },
  {
    emoji: '[爱你]',
    name: '爱你',
    em_code: '/:lvu',
    code: 'wx-88',
  },
  {
    emoji: '[NO]',
    name: 'NO',
    em_code: '/:no',
    code: 'wx-89',
  },
  {
    emoji: '[OK]',
    name: 'OK',
    em_code: '/:ok',
    code: 'wx-90',
  },
  // line7
  {
    emoji: '[爱情]',
    name: '爱情',
    em_code: '/:love',
    code: 'wx-91',
  },
  {
    emoji: '[飞吻]',
    name: '飞吻',
    em_code: '/:<L>',
    code: 'wx-92',
  },
  {
    emoji: '[跳跳]',
    name: '跳跳',
    em_code: '/:jump',
    code: 'wx-93',
  },
  {
    emoji: '[发抖]',
    name: '发抖',
    em_code: '/:shake',
    code: 'wx-94',
  },
  {
    emoji: '[怄火]',
    name: '怄火',
    em_code: '/:<o>',
    code: 'wx-95',
  },
  {
    emoji: '[转圈]',
    name: '转圈',
    em_code: '/:circle',
    code: 'wx-96',
  },
  {
    emoji: '[磕头]',
    name: '磕头',
    em_code: '/:kotow',
    code: 'wx-97',
  },
  {
    emoji: '[回头]',
    name: '回头',
    em_code: '/:turn',
    code: 'wx-98',
  },
  {
    emoji: '[跳绳]',
    name: '跳绳',
    em_code: '/:skip',
    code: 'wx-99',
  },
  {
    emoji: '[投降]',
    name: '投降',
    em_code: '/:oy',
    code: 'wx-100',
  },
  {
    emoji: '[激动]',
    name: '激动',
    em_code: '/:#-0',
    code: 'wx-101',
  },
  {
    emoji: '[乱舞]',
    name: '乱舞',
    em_code: '/:hiphot',
    code: 'wx-102',
  },
  {
    emoji: '[献吻]',
    name: '献吻',
    em_code: '/:kiss',
    code: 'wx-103',
  },
  {
    emoji: '[左太极]',
    name: '左太极',
    em_code: '/:<&',
    code: 'wx-104',
  },
  {
    emoji: '[右太极]',
    name: '右太极',
    em_code: '/:&>',
    code: 'wx-105',
  },
  // 2020微信新加的表情
  {
    emoji: '[吃瓜]',
    name: '吃瓜',
    em_code: '',
    code: 'wx-new-1',
  },
  {
    emoji: '[Emm]',
    name: 'Emm',
    em_code: '',
    code: 'wx-new-2',
  },
  {
    emoji: '[哇]',
    name: '哇',
    em_code: '',
    code: 'wx-new-3',
  },
  {
    emoji: '[社会社会]',
    name: '社会社会',
    em_code: '',
    code: 'wx-new-4',
  },

  {
    emoji: '[汗]',
    name: '汗',
    em_code: '',
    code: 'wx-new-5',
  },
  {
    emoji: '[加油]',
    name: '加油',
    em_code: '',
    code: 'wx-new-6',
  },
  {
    emoji: '[天啊]',
    name: '天啊',
    em_code: '',
    code: 'wx-new-7',
  },
  {
    emoji: '[好的]',
    name: '好的',
    em_code: '',
    code: 'wx-new-8',
  },
  {
    emoji: '[打脸]',
    name: '打脸',
    em_code: '',
    code: 'wx-new-9',
  },
  {
    emoji: '[旺柴]',
    name: '旺柴',
    em_code: '',
    code: 'wx-new-10',
  },
];

export default emojis_wx;
